Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: cassiebarerra.com
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: False
        BlockPublicPolicy: False
        IgnorePublicAcls: False
        RestrictPublicBuckets: Test